platform :ios, '17.0'

target 'appblocker' do
  use_frameworks!

  # Google ML Kit Pose Detection (Accurate model)
  pod 'GoogleMLKit/PoseDetectionAccurate', '8.0.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
